language: python
python:
#   - "2.7.12"   # Errors trying to install Python 2.7.12
#   - "3.5.2"    # Errors trying to install Python 3.5.2
#   - "2.7"      # Python 2.7.9 and pip 6.0.7
    - "3.5"      # Python 3.5.0 and pip 7.1.2
    - "nightly"  # Python 3.6.0a0 and pip 7.1.2  # currently points to 3.6-dev
# command to install dependencies
install:
#   - pip install --upgrade pip  # pip 6.0.8 vs. pip 8.1.2
#   - pip --version  # This does not work
#   - pip install -r requirements.txt
    - pip install flake8
# preflight
before_script:
  flake8 . #  --max-line-length=100  # --exit-zero  # 79 characters was for punchcards!
# command to run tests
# script: flake8 .  # nosetests
script: ls  # nosetests
notifications:
  on_success: change
  on_failure: always
